version: "3"
services:
  my-node-app:
    build: .
    ports:
      - "5001:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=4000
    # env_file:
    #   - ./.env

